name: Integration Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - run: npm i
    - run: npm run test:integration
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: integration-tests
        path: ${{ github.workspace }}/tests/artifacts/
        retention-days: 5
