name: Run unit tests
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn
    - run: yarn test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: unit-tests
        path: ${{ github.workspace }}/coverage/
        retention-days: 5
